# Site settings
title: Richard Chen
description: Richard Chen site
favicon: /assets/img/avatar.jpg
baseurl:
url: http://jseed.xyz
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/NanJing

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
